### ISSUE TITLE
DNS discovery

### ISSUE THREAD

**Issue by hopeyen** [graphops/graphcast-sdk#15]
### Motivation

Allow [DNS discovery](https://rfc.vac.dev/spec/36/#dns-discovery) to peers in the `graphcast` network

### Expectation
Have boot nodes running with multiAddr field advertised (to be run on infura)
Set up a DNS discoverable ENR tree and get its url
Individual nodes have `dns_discovery` turned on should be able to  join the network upon initiation.

### Tasks
Infura
Node instances running with `advertise_addr` ([multiaddrs](https://rfc.vac.dev/spec/31/#multiaddrs-enr-key) )
Set up [ENR record](https://rfc.vac.dev/spec/31/) to contain the advertised address
Node `waku2` key field set value to `relay` (I think it should just be 0) 

SDK updates 
- New node peer connect method to use `node_handle.dns_discovery()` for the peer list,
- Iterate over peer list for `node_handle.connect_peer_with_address()`, 
- Can check statuses with `listen_addresses`

- [x] Static node list solved
- [x] DNS discovery with peer instances #31 
- [ ] Setup DNS on Cloudflare with ENR tree  #34 
- [ ] Infrastructure: Multiple nwaku nodes
- [ ] Infrastructure: Automate tree update work flow
- [ ] Discv5 when waku bindings support the feature
