### ISSUE TITLE
[EPIC] Community

### ISSUE THREAD

**Issue by hopeyen** [graphops/graphcast-sdk#239]
- [ ] Understand what help users the most
- [ ] Proactively reaching to the community for feedbacks
- [ ] Regularly monitor the adoption metrics

**Comment by axiomatic-aardvark** [comment]
we can use 3la to track number of nodes on a certain pubsub topic

**Comment by axiomatic-aardvark** [comment]
All high level and abstract user feedback/questions/sggestions/etc go here https://github.com/graphops/graphcast-meta

**Comment by axiomatic-aardvark** [comment]
on feedback - we should create small guides/tutorials and send them to the public

**Comment by axiomatic-aardvark** [comment]
closing this as Issues like this should go in [graphcast-meta](https://github.com/graphops)

**Comment by hopeyen** [comment]
@axiomatic-aardvark sure, could you make an issue there and link it here?

**Comment by axiomatic-aardvark** [comment]
Sure thing, here are specific Issues that sprung up from this one

1. Monitoring usage/adoption - https://github.com/graphops/graphcast-meta/issues/9
2. Survey users - https://github.com/graphops/graphcast-meta/issues/10
3. Record guide - https://github.com/graphops/graphcast-meta/issues/4
